### ISSUE TITLE
AttributeError: module 'pyrep.backend.sim' has no attribute 'simRemoveBanner

### ISSUE THREAD

**Issue by t-thanh** [larocs/SAC_uav#1]
Hi,

Nice work. I try to reproduce your result and got success at training the model in my computer, but for the evaluation, I got error `AttributeError: module 'pyrep.backend.sim' has no attribute 'simRemoveBanner'
` 

for 
```  
File "evaluate.py", line 47, in rollouts
    sim.simRemoveBanner(sim.sim_handle_all)
```
Is that because of different version of Pyrep? I have 4.1.0 (newest one).

Best regards,

**Comment by kaelgabriel** [comment]
Hi, I am glad that you liked it.

I forgot about that, it is just a snippet that I have written in the  pyrep/backend/sim.py
```

def simTransformVector(matrix,vect):
    #multiplied_vector = ffi.new('float[3]')
    vect = lib.simTransformVector(matrix, vect)
    return(vect)

def simAddBanner(label,size,options, positionAndEulerAngles,  parentObjectHandle):
    black=[0,0,0,0,0,0,0,0,0,0,0,0]
    purple=[0,0,0,0,0,0,0,0,0,1,0,1]
    lib.simAddBanner(label,size,options, positionAndEulerAngles, parentObjectHandle, black, purple)


def simRemoveBanner(bannerID):
    lib.simRemoveBanner(bannerID)

```

You can comment the banner lines, they are just for visuals.

Gabriel
